# Generated by Django 5.1.2 on 2024-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('hourly_rate', models.IntegerField()),
                ('specialization', models.CharField(max_length=40)),
                ('certification', models.CharField(max_length=30)),
                ('availability', models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
