# Generated by Django 5.1.2 on 2024-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('UM', 'under maintenance'), ('A', 'Available')], max_length=30)),
                ('last_maintenance', models.DateTimeField()),
                ('next_maintenance', models.DateTimeField()),
            ],
        ),
    ]
