# Generated by Django 5.1.2 on 2024-10-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Annually'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=50)),
                ('price', models.IntegerField()),
                ('duration_in_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membershiptype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
